[projeto]
nome = "Report Automator"
autor = "Rafael Pereira"
mes = 2
ano = 2026

[arquivos]
linha_cabecalho = 4
default_template = "assets/template.xlsx"
user_template = "data/input/user_template.xlsx"
dados_origem = "data/input/planilha_exemplo.xlsx"

[posicoes]
celula_data = "E3"

[colunas]
data = "Data"
servico = "Descrição do serviço"
bairro = "Bairro"

[mapeamento]
manual = "B15"
mecanica = "B20"
semaforica = "B10"
vertical = "B25"
